version: '3'

services:
  jenkins:
    container_name: 'jenkins'
    image: jenkins/jenkins
    ports: 
      - "8080:8080"
    volumes:
      - "$PWD/jenkins:/var/jenkins"
    networks:
      - net
  centos-host:
    container_name: centos-host
    image: centos
    build:
      context: centos
    networks:
      - net
networks:
  net:

